services:
  buildbot-worker:
    image: localhost/bsdpod-x64-buildbot-worker:0.0.5
    tty: true
    nohosts: false
    build: .
    pull_policy: build
    volumes:
        - /tmp/podman-tmp:/tmp/podman-build
    network: podman


networks:
  default:
    external:
      name: podman
